apiVersion: v1
kind: Service
metadata:
  name: hellojs
  namespace: nonprod
spec:
  selector:
    app: hellojs
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP